import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';
import { fighters } from '../data/fighters';
import { Printer, Copy, Check } from 'lucide-react';
export default function FighterDetailsPage() {
  const { id } = useParams(); const { isTelugu, t } = useLanguage(); const [copied,setCopied] = useState(false); const fighter = fighters.find(f=>f.id===id);
  if (!fighter) return <div className="p-12 text-center font-ntr"><Link to="/fighters">{t('common.back')}</Link></div>;
  const rows = [[isTelugu?'పేరు':'Name',isTelugu?fighter.nameTe:fighter.nameEn],[isTelugu?'ప్రాంతం':'Place',isTelugu?fighter.placeTe:fighter.placeEn],[isTelugu?'జిల్లా':'District',isTelugu?fighter.districtTe:fighter.districtEn],[isTelugu?'సంవత్సరం':'Year',fighter.year],[isTelugu?'జైలు శిక్ష':'Imprisonment duration',isTelugu?fighter.jailDurationTe:fighter.jailDurationEn],[isTelugu?'జరిమానా':'Fine',isTelugu?fighter.fineTe:fighter.fineEn],[isTelugu?'కొరడా దెబ్బలు':'Korada Debbalu',isTelugu?fighter.koradaDebbaluTe:fighter.koradaDebbaluEn]];
  const copy = async () => { await navigator.clipboard?.writeText(`${isTelugu?fighter.nameTe:fighter.nameEn}. Godavari Freedom Archive.`); setCopied(true); setTimeout(()=>setCopied(false),1500); };
  return <div className="min-h-screen bg-[#FAF7F0] py-8 px-4 sm:px-6 font-ntr"><div className="max-w-3xl mx-auto"><div className="no-print flex justify-between mb-5"><Link className="text-[#781D22] font-bold" to="/fighters">← {t('common.back')}</Link><span className="flex gap-2"><button onClick={copy} className="border p-2 text-xs">{copied?<Check className="w-4 h-4"/>:<Copy className="w-4 h-4"/>}</button><button onClick={()=>window.print()} className="bg-[#781D22] text-white p-2 text-xs flex gap-1"><Printer className="w-4 h-4"/>{t('fighterDetails.printDossier')}</button></span></div><article className="bg-white border-4 border-[#1C1917] p-6 sm:p-10"><p className="text-center text-xs text-[#8B5A2B] mb-3">{isTelugu?'గోదావరి స్వాతంత్ర్య ఆర్కైవ్ • రికార్డు':'GODAVARI FREEDOM ARCHIVE • RECORD'}</p><h1 className="font-gurajada text-5xl text-center leading-[1.25] pb-6 border-b-2 border-[#1C1917]">{isTelugu?fighter.nameTe:fighter.nameEn}</h1><dl className="divide-y divide-[#D6CFC7] mt-5">{rows.map(([label,value])=><div key={label} className="grid grid-cols-1 sm:grid-cols-3 gap-2 py-4 leading-relaxed"><dt className="font-semibold text-[#781D22]">{label}</dt><dd className="sm:col-span-2 text-[#1C1917]">{value}</dd></div>)}</dl></article></div></div>;
}
