import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';
import EditorialHero from '../components/home/EditorialHero';
import StatsStrip from '../components/home/StatsStrip';
import PriceOfFreedom from '../components/home/PriceOfFreedom';
import SectionHeading from '../components/common/SectionHeading';
import SearchBar from '../components/common/SearchBar';
import FighterGrid from '../components/fighters/FighterGrid';
import ArtifactCard from '../components/archive/ArtifactCard';
import ImageLightbox from '../components/common/ImageLightbox';
import { fighters } from '../data/fighters'; import { artifacts } from '../data/artifacts'; import { events } from '../data/events'; import { articles as stories } from '../data/articles';
export default function HomePage() {
 const {isTelugu,t}=useLanguage(); const [query,setQuery]=useState(''); const [artifact,setArtifact]=useState(null); const found=fighters.filter(f=>!query||[f.nameTe,f.nameEn,f.placeTe,f.placeEn,String(f.year)].some(v=>v.toLowerCase().includes(query.toLowerCase())));
 return <div className="bg-[#FAF7F0]"><EditorialHero/><StatsStrip/><section className="py-12 px-4 border-b border-[#D6CFC7]"><div className="max-w-7xl mx-auto space-y-6"><SectionHeading kicker={isTelugu?'రికార్డుల అన్వేషణ':'RECORD SEARCH'} title={t('search.title')} subtitle={t('search.subtitle')}/><SearchBar value={query} onChange={setQuery}/>{query&&<FighterGrid fighters={found}/>}<Link to="/fighters" className="font-ntr text-sm font-bold text-[#781D22]">{isTelugu?'అన్ని గోదావరి సమరయోధులను చూడండి →':'Browse all Godavari freedom fighters →'}</Link></div></section><section className="py-12 px-4 border-b border-[#D6CFC7]"><div className="max-w-7xl mx-auto"><SectionHeading kicker={isTelugu?'ఉభయ గోదావరి రికార్డులు':'EAST & WEST GODAVARI RECORDS'} title={isTelugu?'గోదావరి స్వాతంత్ర్య సమరయోధులు':'Godavari Freedom Fighters'} subtitle={isTelugu?'చిత్రాలు లేదా జీవితచరిత్రలు లేకుండా, అందుబాటులో ఉన్న ఏడు రికార్డు వివరాలు మాత్రమే.':'Only the seven available record fields, with no portraits or biographies.'}/><FighterGrid fighters={fighters.slice(0,6)}/></div></section><PriceOfFreedom/><section className="py-12 px-4 border-b border-[#D6CFC7]"><div className="max-w-7xl mx-auto"><SectionHeading kicker={t('archiveSection.kicker')} title={t('archiveSection.title')} subtitle={t('archiveSection.subtitle')} actionButton={<Link to="/archive" className="text-[#781D22] font-ntr font-bold text-sm">{isTelugu?'ఆర్కైవ్ చూడండి →':'View archive →'}</Link>}/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{artifacts.slice(0,4).map(a=><ArtifactCard key={a.id} artifact={a} onSelect={setArtifact}/>)}</div></div></section><section className="py-12 px-4 border-b border-[#D6CFC7]"><div className="max-w-7xl mx-auto"><SectionHeading kicker={t('timeline.kicker')} title={t('timeline.title')} subtitle={t('timeline.subtitle')}/><div className="grid md:grid-cols-3 gap-4">{events.slice(0,3).map(e=><div className="bg-white border p-4" key={e.id}><p className="font-gurajada text-3xl text-[#781D22]">{e.year}</p><h3 className="font-gurajada text-2xl leading-[1.25]">{isTelugu?e.titleTe:e.titleEn}</h3></div>)}</div><Link to="/timeline" className="inline-block mt-5 font-ntr font-bold text-[#781D22]">{isTelugu?'పూర్తి కాలక్రమం →':'Full timeline →'}</Link></div></section><section className="py-12 px-4"><div className="max-w-7xl mx-auto"><SectionHeading kicker={isTelugu?'ప్రధాన వ్యాసం':'LEAD ARTICLE'} title={isTelugu?'మహాత్మా గాంధీ జీవిత చరిత్ర':'Mahatma Gandhi: A Life Story'} subtitle={isTelugu?'వ్యాసాల విభాగం నుంచి ప్రధాన పఠనం.':'Featured reading from the articles section.'}/><Link to={`/articles/${stories[0].id}`} className="font-ntr font-bold text-[#781D22]">{t('stories.readArticle')}</Link></div></section><ImageLightbox artifact={artifact} isOpen={!!artifact} onClose={()=>setArtifact(null)}/></div>;
}
